// ─────────────────────────────────────────────────────────────
// data.js — every piece of raw content the storefront renders.
// Swap the image seeds/urls or extend arrays to reskin the site.
// ─────────────────────────────────────────────────────────────

const img = (seed, w = 800, h = 800) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const brand = {
  name: 'Ram Gaming World',
  tagline: 'Everyday goods, chosen well',
};

export const nav = {
  links: ['All', "Today's Deals", 'Gift Cards', 'New Arrivals'],
};

// Icon-style quick category row — shown as its own section under the header.
export const iconCategories = [
  { id: 'all', name: 'View All', icon: img('icon', 200, 200) , img : "/img/ps5.png" } , 
  { id: 'consoles', name: 'GameBoy', icon: img('icon-consoles', 200, 200),img : "/img/console.jpg" },
  { id: 'laptops', name: 'Controller', icon: img('icon-laptops', 200, 200),img : "/img/controller.jpg" },
  { id: 'smartphones', name: 'Games', icon: img('icon-phones', 200, 200),img : "/img/game1.jpg" },
  { id: 'cameras', name: 'Headphone', icon: img('icon-cameras', 200, 200),img : "/img/headphone.jpg" },
  { id: 'lenses', name: 'Monitor', icon: img('icon-lens', 200, 200),img : "/img/monitor.jpg" },
  { id: 'controllers', name: 'Nintendo', icon: img('icon-controllers', 200, 200),img : "/img/nintendo.png" },
  { id: 'accessories', name: 'Console', icon: img('icon-accessories', 200, 200),img : "/img/ps3.png" },
  { id: 'smart-devices', name: 'Ps4', icon: img('icon-smart', 200, 200),img : "/img/ps4.jpg" },

];

// Estimated EMI helper — a simple "or $X/mo" line under the price, not real financing math.
export const estimateEmi = (price, months = 6) => (price / months).toFixed(2);

export const heroSlide = {
  eyebrow: 'Featured edit',
title: 'Game nights, seriously upgraded',

copy:
  'Consoles, controllers, and gaming essentials — everything you need to build a setup made for better play.',
  cta: 'Shop the edit',
  image: img('hero-headphones', 900, 900),
};

export const quickLinks = [
  { label: 'Hi, welcome back', sub: 'See your picks for today', icon: 'user', to: '/' },
  { label: 'Your orders', sub: 'Track & manage', icon: 'box', to: '/cart' },
  { label: 'Audio', sub: 'Up to 30% off', icon: 'headphones', to: '/' },
  { label: 'Home & Kitchen', sub: 'Up to 30% off', icon: 'home', to: '/' },
];

export const categories = [
  { id: 'beauty', name: 'Console', img: "/img/ps5.png", image: img('cat-beauty', 500, 500) },
  { id: 'computers', name: 'Games', img: "/img/game6.png", image: img('cat-laptop', 500, 500) },
  { id: 'gaming', name: 'Controller', img: "/img/controller.png" , image: img('cat-vr', 500, 500) },
  { id: 'toys', name: 'Other', img: "/img/headphone.png" , image: img('cat-toy', 500, 500) },
];

export const promoStrips = [
  {
    id: 'basics',
    title: 'Verve Basics',
    copy: "Today's deals, lightning deals, and limited-time discounts.",
    image: img('promo-controller', 400, 300),
  },
  {
    id: 'deals',
    title: 'Deals & Promotions',
    copy: "Today's deals, lightning deals, and limited-time discounts.",
    image: img('promo-clock', 400, 300),
  },
];

export const deliveryBanner = {
  title: 'Verve delivers to you',
  copy:
    'Worldwide shipping — we ship to over 100 countries and regions, right at your doorstep.',
  cta: 'See shipping details',
  image: img('promo-dog-box', 900, 700),
};

// ── Product catalogue ───────────────────────────────────────
// category: computers | audio | kitchen | footwear | wearables | accessories
// export const products = [
//   {
//     id: 'p-headphone-black',
//     name: 'Aro 400BT Wireless Headphones',
//     category: 'audio',
//     brand: 'Aro',
//     price: 125.0,
//     compareAt: 149.0,
//     rating: 4.6,
//     reviews: 812,
//     tag: 'Deal',
//     colors: ['#171512', '#6F6A63', '#BC7E33'],
//     img: '/img/headphone.jpg' ,
//     images: [img('headphone-1'), img('headphone-2'), img('headphone-3'), img('headphone-4')],
//     short: 'Over-ear wireless headphones with 40-hour battery life and adaptive noise cancelling.',
//     description:
//       'The Aro 400BT pairs plush, breathable ear cushions with a 40mm driver tuned for warm, balanced sound. Adaptive noise cancelling adjusts to your environment in real time, and a 40-hour battery means they rarely see the charging case.',
//     specs: [
//       { label: 'Battery life', value: 'Up to 40 hours' },
//       { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm jack' },
//       { label: 'Weight', value: '254 g' },
//       { label: 'Noise cancelling', value: 'Adaptive ANC' },
//     ],
//     stock: 24,
//   },
//   {
//     id: 'p-laptop-studio',
//     name: 'Nintendo Gameboy',
//     category: 'computers',
//     brand: 'Northline',
//     price: 1299.0,
//     compareAt: null,
//     rating: 4.8,
//     reviews: 356,
//     tag: 'New',
//     colors: ['#171512', '#E7E3DC'],
//     img: '/img/console.png' ,
//     images: [img('laptop-1'), img('laptop-2'), img('laptop-3')],
//     short: '14" 2.8K display, 32GB RAM, all-day battery for design and code.',
//     description:
//       'A magnesium-alloy body keeps the Studio 14 light without feeling fragile. The 2.8K display is calibrated for accurate color out of the box, and 32GB of unified memory keeps large projects moving without a stutter.',
//     specs: [
//       { label: 'Display', value: '14" 2.8K, 120Hz' },
//       { label: 'Memory', value: '32GB unified' },
//       { label: 'Storage', value: '1TB SSD' },
//       { label: 'Battery', value: 'Up to 18 hours' },
//     ],
//     stock: 11,
//   },
//   {
//     id: 'p-vr-headset',
//     name: 'Halo VR Headset',
//     category: 'gaming',
//     brand: 'Halo',
//     price: 399.0,
//     compareAt: 449.0,
//     rating: 4.4,
//     reviews: 201,
//     tag: 'Deal',
//     colors: ['#171512'],
//     img: '/img/ps5.png' ,
//     images: [img('vr-1'), img('vr-2'), img('vr-3')],
//     short: 'Standalone mixed-reality headset with 4K-per-eye clarity.',
//     description:
//       'Halo tracks your space without external sensors, blending full-color passthrough with crisp 4K-per-eye visuals. Swappable foam padding keeps long sessions comfortable.',
//     specs: [
//       { label: 'Display', value: '4K per eye, 120Hz' },
//       { label: 'Tracking', value: 'Inside-out, 6DoF' },
//       { label: 'Storage', value: '256GB' },
//       { label: 'Weight', value: '512 g' },
//     ],
//     stock: 8,
//   },
//   {
//     id: 'p-plush-bear',
//     name: 'Wander Plush Puppy',
//     category: 'toys',
//     brand: 'Wander',
//     price: 24.5,
//     compareAt: null,
//     rating: 4.9,
//     reviews: 540,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#DDAE6C', '#E7E3DC'],
//     images: [img('plush-1'), img('plush-2')],
//     short: 'Soft, weighted plush companion for nap time and shelf styling alike.',
//     description:
//       'Hand-finished with a soft cotton-blend coat and gently weighted for comforting cuddles. Machine washable and built to survive years of love.',
//     specs: [
//       { label: 'Height', value: '32 cm' },
//       { label: 'Material', value: 'Cotton-poly blend' },
//       { label: 'Care', value: 'Machine washable' },
//     ],
//     stock: 60,
//   },
//   {
//     id: 'p-sneaker-black',
//     name: 'Puma AXIS TR Boot',
//     category: 'footwear',
//     brand: 'Puma',
//     price: 150.99,
//     compareAt: null,
//     rating: 4.5,
//     reviews: 128,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#171512'],
//     images: [img('shoe-1'), img('shoe-2')],
//     short: 'Trail-ready training boot with reinforced ankle support.',
//     description:
//       'Built for mixed terrain, the AXIS TR pairs a grippy lugged outsole with a supportive, reinforced ankle collar for lateral stability during training.',
//     specs: [
//       { label: 'Upper', value: 'Ripstop textile' },
//       { label: 'Outsole', value: 'Rubber, multi-directional lugs' },
//       { label: 'Fit', value: 'True to size' },
//     ],
//     stock: 33,
//   },
//   {
//     id: 'p-sneaker-air',
//     name: 'Nike Air High-Light Red',
//     category: 'footwear',
//     brand: 'Nike',
//     price: 86.0,
//     compareAt: null,
//     rating: 4.3,
//     reviews: 96,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#FDFCFA', '#BC7E33'],
//     images: [img('shoe-3'), img('shoe-4')],
//     short: 'Lightweight everyday trainer with responsive cushioning.',
//     description:
//       'A breathable knit upper and a responsive midsole make this the trainer you reach for on days you are on your feet from morning to night.',
//     specs: [
//       { label: 'Upper', value: 'Engineered knit' },
//       { label: 'Midsole', value: 'Foam cushioning' },
//       { label: 'Fit', value: 'True to size' },
//     ],
//     stock: 47,
//   },
//   {
//     id: 'p-sneaker-adidas',
//     name: 'Adidas Fusion Storm Winter',
//     category: 'footwear',
//     brand: 'Adidas',
//     price: 79.97,
//     compareAt: 94.0,
//     rating: 4.2,
//     reviews: 73,
//     tag: 'Deal',
//       img: '/img/ps5.png' ,
//     colors: ['#171512', '#6F6A63'],
//     images: [img('shoe-5'), img('shoe-6')],
//     short: 'Water-resistant winter runner with thermal lining.',
//     description:
//       'A water-resistant upper and thermal lining keep feet warm and dry through cold-weather miles, without weighing the shoe down.',
//     specs: [
//       { label: 'Upper', value: 'Water-resistant mesh' },
//       { label: 'Lining', value: 'Thermal fleece' },
//       { label: 'Fit', value: 'True to size' },
//     ],
//     stock: 19,
//   },
//   {
//     id: 'p-sneaker-cloud',
//     name: 'Nike CloudFoam Pure Running',
//     category: 'footwear',
//     brand: 'Nike',
//     price: 68.99,
//     compareAt: null,
//     rating: 4.6,
//     reviews: 210,
//     tag: null,
//       img: '/img/ps5.png' ,
//     colors: ['#171512'],
//     images: [img('shoe-7'), img('shoe-8')],
//     short: 'Soft-landing daily runner built for long mileage.',
//     description:
//       'CloudFoam midsoles absorb impact on longer runs, while a snug knit collar keeps the foot locked in through every stride.',
//     specs: [
//       { label: 'Midsole', value: 'CloudFoam' },
//       { label: 'Upper', value: 'Knit mesh' },
//       { label: 'Fit', value: 'True to size' },
//     ],
//     stock: 40,
//   },
//   {
//     id: 'p-cable-lightning',
//     name: 'Verve Basics Lightning to USB Cable',
//     category: 'accessories',
//     brand: 'Verve Basics',
//     price: 15.99,
//     compareAt: null,
//     rating: 4.5,
//     reviews: 1290,
//     tag: null,
//       img: '/img/ps5.png' ,
//     colors: ['#FDFCFA'],
//     images: [img('cable-1'), img('cable-2')],
//     short: 'Braided 1.8m charge & sync cable, MFi certified.',
//     description:
//       'A reinforced braided jacket and MFi certification make this cable a reliable everyday charger — rated for 10,000+ bend cycles.',
//     specs: [
//       { label: 'Length', value: '1.8 m' },
//       { label: 'Certification', value: 'MFi certified' },
//     ],
//     stock: 200,
//   },
//   {
//     id: 'p-monitor-24',
//     name: 'Skyworth O-Series 24" 1080p Monitor',
//     category: 'computers',
//     brand: 'Skyworth',
//     price: 129.97,
//     compareAt: null,
//     rating: 4.4,
//     reviews: 88,
//     tag: null,
//     colors: ['#171512'],
//     img: 'console.png' ,
//     images: [img('monitor-1'), img('monitor-2')],
//     short: '24" IPS monitor with slim bezels and 75Hz refresh.',
//     description:
//       'A crisp IPS panel with slim bezels makes this an easy multi-monitor upgrade for a home office, tuned for accurate color at a friendly price.',
//     specs: [
//       { label: 'Panel', value: '24" IPS, 1080p' },
//       { label: 'Refresh', value: '75Hz' },
//       { label: 'Ports', value: 'HDMI, VGA' },
//     ],
//     stock: 15,
//   },
//   {
//     id: 'p-cooker-instant',
//     name: 'Ps4 Controller ',
//     category: 'kitchen',
//     brand: 'Instant',
//     price: 79.0,
//     compareAt: null,
//     rating: 4.7,
//     reviews: 3021,
//     tag: null,
//     colors: ['#6F6A63'],
//     img: 'controller.jpg' ,
//     images: [img('cooker-1'), img('cooker-2')],
//     short: 'Ps4 controllers compatible with ps4, computers, laptops.',
//     description:
//       'Seven appliances in one, the Duo takes the guesswork out of weeknight cooking with pre-set programs for rice, beans, yogurt and more.',
//     specs: [
//       { label: 'Capacity', value: '6 quart' },
//       { label: 'Programs', value: '7 built-in' },
//       { label: 'Material', value: 'Stainless steel insert' },
//     ],
//     stock: 22,
//   },
//   {
//     id: 'p-hairdryer-philips',
//     name: 'Witcher 3',
//     category: 'accessories',
//     brand: 'Philips',
//     price: 24.99,
//     compareAt: 32.0,
//     rating: 4.3,
//     reviews: 410,
//     tag: 'Deal',
//     colors: ['#171512'],
//     img: 'game1.jpg' ,
//     images: [img('dryer-1'), img('dryer-2')],
//     short: 'Ionic dryer with 3 heat and 2 speed settings.',
//     description:
//       'Ionic technology reduces frizz and cuts drying time, with a cool-shot button to lock in your style once you are done.',
//     specs: [
//       { label: 'Power', value: '1875W' },
//       { label: 'Settings', value: '3 heat / 2 speed' },
//     ],
//     stock: 55,
//   },
//   {
//     id: 'p-pan-greenpan',
//     name: 'xbox controller"',
//     category: 'kitchen',
//     brand: 'GreenPan',
//     price: 59.94,
//     compareAt: 69.99,
//     rating: 4.8,
//     reviews: 615,
//     tag: 'Deal',
//     colors: ['#171512'],
//     img: 'controller2.jpg' ,
//     images: [img('pan-1'), img('pan-2')],
//     short: 'Ceramic non-stick, stacks flat to save cabinet space.',
//     description:
//       'A hard-anodized body resists warping while a ceramic non-stick coating means less oil and easier cleanup. Nests flat with the rest of the set.',
//     specs: [
//       { label: 'Size', value: '12 inch' },
//       { label: 'Coating', value: 'Ceramic non-stick' },
//       { label: 'Oven safe', value: 'Up to 350°F' },
//     ],
//     stock: 26,
//   },
//   {
//     id: 'p-mouse-xiaomi',
//     name: 'monitor',
//     category: 'computers',
//     brand: 'Xiaomi',
//     price: 20.99,
//     compareAt: null,
//     rating: 4.5,
//     reviews: 980,
//     tag: null,
//     colors: ['#E7E3DC'],
//     images: [img('mouse-1'), img('mouse-2')],
//     img: 'controller2.jpg' ,
//     short: 'Silent-click wireless mouse, 4-month battery life.',
//     description:
//       'A quiet-click switch and a slim aluminum shell make this an easy mouse to carry, with up to four months of use per charge.',
//     specs: [
//       { label: 'Connectivity', value: 'Bluetooth 4.2' },
//       { label: 'Battery', value: 'Up to 4 months' },
//     ],
//     stock: 70,
//   },
//   {
//     id: 'p-watch-instant',
//     name: 'Nintendo switch',
//     category: 'wearables',
//     brand: 'Pulse',
//     price: 400.6,
//     compareAt: null,
//     rating: 4.4,
//     reviews: 142,
//     tag: null,
//     colors: ['#171512'],
//     img: '/img/game5.jpg' ,
//     images: [img('watch-1'), img('watch-2')],
//     short: 'Always-on display, 10-day battery, full health tracking.',
//     description:
//       'Track sleep, heart rate and workouts with a battery that lasts up to ten days, wrapped in a sapphire-glass case built to last.',
//     specs: [
//       { label: 'Display', value: 'Always-on AMOLED' },
//       { label: 'Battery', value: 'Up to 10 days' },
//       { label: 'Water resistance', value: '5 ATM' },
//     ],
//     stock: 18,
//   },
//   {
//     id: 'p-headphone-razer',
//     name: 'Ps3 console',
//     category: 'audio',
//     brand: 'Razer',
//     price: 45.45,
//     compareAt: 59.99,
//     rating: 4.1,
//     reviews: 63,
//     tag: 'Deal',
//     img: 'ps3.png' ,
//     colors: ['#171512'],
//     images: [img('razer-1'), img('razer-2')],
//     short: 'Gaming headset with detachable boom mic.',
//     description:
//       'Tuned for competitive clarity, with a detachable boom mic and plush ear cushions for marathon sessions.',
//     specs: [
//       { label: 'Driver', value: '50mm' },
//       { label: 'Mic', value: 'Detachable boom' },
//     ],
//     stock: 30,
//   },
//   {
//     id: 'p-earbuds-sennheiser',
//     name: 'Ps4 Pro console',
//     category: 'audio',
//     brand: 'Sennheiser',
//     price: 20.5,
//     compareAt: null,
//     rating: 4.3,
//     reviews: 175,
//     tag: null,
//     img: 'ps4.png' ,
//     colors: ['#171512'],
//     images: [img('sen-1'), img('sen-2')],
//     short: 'Compact true wireless earbuds with punchy bass.',
//     description:
//       'A compact fit and a bass-forward tuning make these an easy grab for commutes and workouts alike, with a pocketable charging case.',
//     specs: [
//       { label: 'Battery', value: 'Up to 9 hours + case' },
//       { label: 'Connectivity', value: 'Bluetooth 5.2' },
//     ],
//     stock: 44,
//   },
//   {
//     id: 'p-earbuds-xiaomi',
//     name: 'Spiderman remasterd',
//     category: 'audio',
//     brand: 'Xiaomi',
//     price: 67.0,
//     compareAt: 110.0,
//     rating: 4.2,
//     reviews: 302,
//     tag: 'Deal',
//     img: 'game3.jpg' ,
//     colors: ['#171512'],
//     images: [img('mi-earbud-1'), img('mi-earbud-2')],
//     short: 'ANC true wireless earbuds with low-latency gaming mode.',
//     description:
//       'Active noise cancelling and a low-latency gaming mode make these a flexible daily pair, whether you are on a call or mid-match.',
//     specs: [
//       { label: 'ANC', value: 'Up to 35dB' },
//       { label: 'Latency mode', value: '88ms gaming mode' },
//     ],
//     stock: 37,
//   },
// ];
export const products = [
  {
    id: 'p-ps5',
    name: 'PlayStation 5 Console',
    category: 'gaming',
    brand: 'Sony',
    price: 499.99,
    compareAt: null,
    rating: 4.8,
    reviews: 1250,
    tag: 'New',
    colors: ['#FDFCFA'],
    img: '/img/ps5.png',
    images: [img('ps5'), img('ps5controller')],
    short: 'Next-generation PlayStation console with fast loading and 4K gaming.',
    description:
      'The PlayStation 5 delivers fast loading, immersive gameplay and support for stunning 4K gaming.',
    specs: [
      { label: 'Resolution', value: 'Up to 4K' },
      { label: 'Storage', value: '825GB SSD' },
      { label: 'Brand', value: 'Sony' },
    ],
    stock: 12,
  },

  {
    id: 'p-ps4',
    name: 'PlayStation 4 Console',
    category: 'gaming',
    brand: 'Sony',
    price: 249.99,
    compareAt: null,
    rating: 4.6,
    reviews: 840,
    tag: 'Deal',
    colors: ['#171512'],
    img: '/img/ps4.png',
    images: [img('ps4'), img('ps4controller')],
    short: 'Classic PlayStation console for a large library of games.',
    description:
      'A dependable PlayStation console with access to a huge collection of games and entertainment.',
    specs: [
      { label: 'Resolution', value: 'Up to 1080p' },
      { label: 'Storage', value: '500GB' },
      { label: 'Brand', value: 'Sony' },
    ],
    stock: 18,
  },

  {
    id: 'p-ps4-pro',
    name: 'PlayStation 4 Pro',
    category: 'gaming',
    brand: 'Sony',
    price: 299.99,
    compareAt: 349.99,
    rating: 4.7,
    reviews: 620,
    tag: 'Deal',
    colors: ['#171512'],
    img: '/img/ps4pro.png',
    images: [img('ps4pro'), img('ps4controller')],
    short: 'Enhanced PS4 console with improved graphics and 4K support.',
    description:
      'The PS4 Pro offers enhanced graphics, smoother performance and support for 4K-ready gaming.',
    specs: [
      { label: 'Resolution', value: 'Up to 4K' },
      { label: 'Storage', value: '1TB' },
      { label: 'Brand', value: 'Sony' },
    ],
    stock: 9,
  },

  {
    id: 'p-ps4-slim',
    name: 'PlayStation 4 Slim',
    category: 'gaming',
    brand: 'Sony',
    price: 229.99,
    compareAt: null,
    rating: 4.6,
    reviews: 510,
    tag: null,
    colors: ['#171512'],
    img: '/img/ps4slim.png',
    images: [img('ps4slim'), img('ps4controller')],
    short: 'Slim PlayStation console with a compact design.',
    description:
      'A smaller PS4 design that keeps the familiar PlayStation gaming experience while taking up less space.',
    specs: [
      { label: 'Resolution', value: 'Up to 1080p' },
      { label: 'Storage', value: '500GB' },
      { label: 'Design', value: 'Slim' },
    ],
    stock: 14,
  },

  {
    id: 'p-xbox',
    name: 'Xbox Console',
    category: 'gaming',
    brand: 'Xbox',
    price: 399.99,
    compareAt: null,
    rating: 4.7,
    reviews: 730,
    tag: 'New',
    colors: ['#171512'],
    img: '/img/xbox.png',
    images: [img('xbox'), img('controller')],
    short: 'Xbox console built for fast, immersive gaming.',
    description:
      'A modern Xbox console designed for smooth gameplay, quick loading and a broad game library.',
    specs: [
      { label: 'Resolution', value: 'Up to 4K' },
      { label: 'Connectivity', value: 'Wi-Fi, HDMI' },
      { label: 'Brand', value: 'Xbox' },
    ],
    stock: 11,
  },

  {
    id: 'p-nintendo',
    name: 'Nintendo Console',
    category: 'gaming',
    brand: 'Nintendo',
    price: 299.99,
    compareAt: null,
    rating: 4.8,
    reviews: 680,
    tag: null,
    colors: ['#E7E3DC'],
    img: '/img/nintendo.png',
    images: [img('nintendo'), img('controller3')],
    short: 'Nintendo gaming console for portable and home entertainment.',
    description:
      'A versatile Nintendo console made for casual gaming, family play and gaming on the go.',
    specs: [
      { label: 'Mode', value: 'Home and portable' },
      { label: 'Display', value: 'HD' },
      { label: 'Brand', value: 'Nintendo' },
    ],
    stock: 16,
  },

  {
    id: 'p-ps5-controller',
    name: 'PS5 Wireless Controller',
    category: 'controllers',
    brand: 'Sony',
    price: 69.99,
    compareAt: 74.99,
    rating: 4.8,
    reviews: 940,
    tag: 'Deal',
    colors: ['#FDFCFA'],
    img: '/img/controller3.png',
    images: [img('ps5controller'), img('controller3')],
    short: 'Wireless PlayStation controller with an ergonomic design.',
    description:
      'A comfortable wireless controller designed for precise PlayStation gaming and long sessions.',
    specs: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Compatibility', value: 'PS5' },
      { label: 'Charging', value: 'USB-C' },
    ],
    stock: 32,
  },

  {
    id: 'p-ps4-controller',
    name: 'PS4 Wireless Controller',
    category: 'controllers',
    brand: 'Sony',
    price: 49.99,
    compareAt: null,
    rating: 4.6,
    reviews: 760,
    tag: null,
    colors: ['#171512'],
    img: '/img/controller.png',
    images: [img('ps4controller'), img('controller')],
    short: 'Wireless controller designed for PlayStation 4 gaming.',
    description:
      'A familiar PlayStation controller with responsive controls and a comfortable grip for everyday gaming.',
    specs: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Compatibility', value: 'PS4' },
      { label: 'Charging', value: 'USB' },
    ],
    stock: 25,
  },

  {
    id: 'p-xbox-controller',
    name: 'Xbox Wireless Controller',
    category: 'controllers',
    brand: 'Xbox',
    price: 59.99,
    compareAt: null,
    rating: 4.7,
    reviews: 590,
    tag: null,
    colors: ['#171512'],
    img: '/img/xboxcontroller.png',
    images: [img('controller2'), img('controller3')],
    short: 'Xbox controller with textured grips and responsive controls.',
    description:
      'An ergonomic Xbox controller made for comfortable gaming with responsive buttons and textured grips.',
    specs: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Compatibility', value: 'Xbox and PC' },
      { label: 'Grip', value: 'Textured' },
    ],
    stock: 28,
  },

  {
    id: 'p-monitor',
    name: 'Gaming Monitor',
    category: 'accessories',
    brand: 'Skyworth',
    price: 129.99,
    compareAt: null,
    rating: 4.5,
    reviews: 210,
    tag: null,
    colors: ['#171512'],
    img: '/img/monitor.jpg',
    images: [img('monitor'), img('console')],
    short: 'Slim monitor for gaming, work and everyday entertainment.',
    description:
      'A clean, slim display that works well for gaming setups, desktops and everyday media.',
    specs: [
      { label: 'Panel', value: 'IPS' },
      { label: 'Resolution', value: '1080p' },
      { label: 'Refresh', value: '75Hz' },
    ],
    stock: 15,
  },

  {
    id: 'p-headphone',
    name: 'Wireless Headphones',
    category: 'audio',
    brand: 'Sony',
    price: 89.99,
    compareAt: 109.99,
    rating: 4.6,
    reviews: 812,
    tag: 'Deal',
    colors: ['#171512'],
    img: '/img/headphone.png',
    images: [img('headphone'), img('sony')],
    short: 'Comfortable wireless headphones for music and gaming.',
    description:
      'Over-ear headphones with a comfortable fit and clear sound for music, videos and gaming.',
    specs: [
      { label: 'Connectivity', value: 'Bluetooth' },
      { label: 'Design', value: 'Over-ear' },
      { label: 'Use', value: 'Music and gaming' },
    ],
    stock: 24,
  },

  {
    id: 'p-witcher-3',
    name: 'The Witcher 3',
    category: 'games',
    brand: 'CD Projekt',
    price: 29.99,
    compareAt: null,
    rating: 4.9,
    reviews: 1250,
    tag: null,
    colors: ['#171512'],
    img: '/img/game1.jpg',
    images: [img('game1'), img('game2')],
    short: 'Open-world action RPG with a large fantasy world to explore.',
    description:
      'Explore a detailed fantasy world, complete quests and battle monsters in this story-driven action RPG.',
    specs: [
      { label: 'Genre', value: 'Action RPG' },
      { label: 'Mode', value: 'Single-player' },
      { label: 'Platform', value: 'Console' },
    ],
    stock: 20,
  },

  {
    id: 'p-spiderman',
    name: 'Spider-Man Remastered',
    category: 'games',
    brand: 'Marvel',
    price: 39.99,
    compareAt: 49.99,
    rating: 4.8,
    reviews: 870,
    tag: 'Deal',
    colors: ['#171512'],
    img: '/img/game3.jpg',
    images: [img('game3'), img('game4')],
    short: 'Action-packed superhero adventure featuring Spider-Man.',
    description:
      'Swing through the city, fight villains and experience a cinematic Spider-Man adventure.',
    specs: [
      { label: 'Genre', value: 'Action adventure' },
      { label: 'Mode', value: 'Single-player' },
      { label: 'Platform', value: 'Console' },
    ],
    stock: 17,
  },
];

// ── Consoles, games & accessories shelf ─────────────────────
// platform is used purely for the client-side filter tabs below the navbar.
export const consolePlatforms = ['All', 'PlayStation 5', 'PlayStation 4', 'Nintendo Switch', 'Xbox', 'Games & CDs'];

// export const consoleProducts = [
//   {
//     id: 'c-ps5-console',
//     name: 'PlayStation 5 Console, Slim',
//     category: 'consoles',
//     platform: 'PlayStation 5',
//     brand: 'Sony',
//     price: 449.0,
//     compareAt: 499.0,
//     rating: 4.9,
//     reviews: 2210,
    
//     tag: 'Deal',
//     colors: ['#FDFCFA', '#171512'],
//     images: [img('ps5-1'), img('ps5-2'), img('ps5-3')],
//     img: '/img/ps5.png' ,
//     short: '1TB SSD, ray tracing, and the DualSense controller included.',
//     description:
//       'A near-instant boot from a custom 1TB SSD, 4K120 output, and full ray-traced lighting make this the console for the latest releases. The redesigned Slim body ships with one DualSense controller.',
//     specs: [
//       { label: 'Storage', value: '1TB SSD' },
//       { label: 'Output', value: '4K @ 120Hz' },
//       { label: 'Controller', value: '1x DualSense included' },
//     ],
//     stock: 14,
//   },
//   {
//     id: 'c-ps4-console',
//     name: 'PlayStation 4 Slim 1TB',
//     category: 'consoles',
//     platform: 'PlayStation 4',
//     brand: 'Sony',
//     price: 249.0,
//     compareAt: 299.0,
//     rating: 4.6,
//     reviews: 4110,
//     tag: 'Deal',
//     img: '/img/ps5.png' ,
//     colors: ['#171512'],
//     images: [img('ps4-1'), img('ps4-2')],
//     short: 'The budget-friendly way into a five-generation game library.',
//     description:
//       'A slim, quiet redesign of the PS4 with a 1TB drive — the easiest way to access a deep back catalogue of exclusives at a friendly price.',
//     specs: [
//       { label: 'Storage', value: '1TB HDD' },
//       { label: 'Output', value: '1080p, HDR' },
//     ],
//     stock: 20,
//   },
//   {
//     id: 'c-switch-oled',
//     name: 'Nintendo Switch OLED Model',
//     category: 'consoles',
//     platform: 'Nintendo Switch',
//     brand: 'Nintendo',
//     price: 349.0,
//     compareAt: null,
//     rating: 4.8,
//     reviews: 3305,
//     tag: 'New',
//     img: '/img/ps5.png' ,
//     colors: ['#171512', '#FDFCFA'],
//     images: [img('switch-1'), img('switch-2'), img('switch-3')],
//     short: '7" OLED screen, enhanced audio, handheld or docked.',
//     description:
//       'A vivid 7-inch OLED screen and a wide adjustable stand make this the most flexible way to play — at your desk, docked to the TV, or on the move.',
//     specs: [
//       { label: 'Display', value: '7" OLED' },
//       { label: 'Storage', value: '64GB (expandable)' },
//       { label: 'Modes', value: 'TV / Tabletop / Handheld' },
//     ],
//     stock: 27,
//   },
//   {
//     id: 'c-xbox-series-x',
//     name: 'Xbox Series X 1TB',
//     category: 'consoles',
//     platform: 'Xbox',
//     brand: 'Microsoft',
//     price: 479.0,
//     compareAt: 519.0,
//     rating: 4.7,
//     reviews: 1876,
//     tag: 'Deal',
//     img: '/img/ps5.png' ,
//     colors: ['#171512'],
//     images: [img('xbox-1'), img('xbox-2')],
//     short: 'The most powerful Xbox yet, with Quick Resume across titles.',
//     description:
//       'True 4K gaming at up to 120fps, with Quick Resume letting you jump between several games instantly. Backward compatible with three generations of titles.',
//     specs: [
//       { label: 'Storage', value: '1TB SSD' },
//       { label: 'Output', value: '4K @ 120fps' },
//     ],
//     stock: 16,
//   },
//   {
//     id: 'c-dualsense',
//     name: 'DualSense Wireless Controller',
//     category: 'consoles',
//     platform: 'PlayStation 5',
//     brand: 'Sony',
//     price: 64.99,
//     compareAt: null,
//     rating: 4.7,
//     reviews: 980,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#FDFCFA', '#171512', '#1F4B43'],
//     images: [img('dualsense-1'), img('dualsense-2')],
//     short: 'Haptic feedback and adaptive triggers for PS5.',
//     description:
//       'Feel the difference between a gravel road and a wooden crate through haptic feedback, with adaptive triggers that add resistance as you play.',
//     specs: [
//       { label: 'Battery', value: 'Up to 12 hours' },
//       { label: 'Connectivity', value: 'Bluetooth / USB-C' },
//     ],
//     stock: 55,
//   },
//   {
//     id: 'c-switch-joycon',
//     name: 'Joy-Con Controller Pair',
//     category: 'consoles',
//     platform: 'Nintendo Switch',
//     brand: 'Nintendo',
//     price: 79.99,
//     compareAt: null,
//     rating: 4.4,
//     reviews: 640,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#1F4B43', '#BC7E33'],
//     images: [img('joycon-1'), img('joycon-2')],
//     short: 'Detachable motion controllers, one for each hand.',
//     description:
//       'Snap them onto the console for handheld play, detach for local multiplayer, or clip into the grip for a traditional controller feel.',
//     specs: [
//       { label: 'Battery', value: 'Up to 20 hours' },
//       { label: 'Features', value: 'HD rumble, motion controls' },
//     ],
//     stock: 38,
//   },
//   {
//     id: 'c-game-spiderman2',
//     name: 'Spider-Man 2 — PS5',
//     category: 'consoles',
//     platform: 'Games & CDs',
//     brand: 'Sony',
//     price: 69.99,
//     compareAt: null,
//     rating: 4.9,
//     reviews: 2540,
//     tag: 'New',
//     img: '/img/ps5.png' ,
//     colors: ['#171512'],
//     images: [img('game-spiderman', 700, 900), img('game-spiderman-2', 700, 900)],
//     short: 'Swing through New York as Peter and Miles, PS5 disc edition.',
//     description:
//       'The web-swinging sequel arrives with a larger map, two playable heroes, and symbiote powers that reshape combat. Physical disc edition for PS5.',
//     specs: [
//       { label: 'Format', value: 'Blu-ray disc' },
//       { label: 'Platform', value: 'PlayStation 5' },
//     ],
//     stock: 42,
//   },
//   {
//     id: 'c-game-zelda',
//     name: 'The Legend of Zelda: Tears of the Kingdom',
//     category: 'consoles',
//     platform: 'Games & CDs',
//     brand: 'Nintendo',
//     price: 59.99,
//     compareAt: null,
//     rating: 4.9,
//     reviews: 3120,
//     tag: null,
//     img: '/img/ps5.png' ,
//     colors: ['#DDAE6C'],
//     images: [img('game-zelda', 700, 900), img('game-zelda-2', 700, 900)],
//     short: 'Explore sky islands and the depths of Hyrule. Switch cartridge.',
//     description:
//       'A sprawling sequel that adds vertical exploration above and below Hyrule, with new fuse and ultrahand building mechanics.',
//     specs: [
//       { label: 'Format', value: 'Game cartridge' },
//       { label: 'Platform', value: 'Nintendo Switch' },
//     ],
//     stock: 50,
//   },
//   {
//     id: 'c-game-fifa24',
//     name: 'EA Sports FC 24',
//     category: 'consoles',
//     platform: 'Games & CDs',
//     brand: 'EA Sports',
//     price: 49.99,
//     compareAt: 69.99,
//     rating: 4.3,
//     reviews: 1450,
//     tag: 'Deal',
//     colors: ['#1F4B43'],
//     img: '/img/ps5.png' ,
//     images: [img('game-fifa', 700, 900), img('game-fifa-2', 700, 900)],
//     short: 'This year\'s club and international football, cross-play enabled.',
//     description:
//       'Updated squads, HyperMotionV animation capture, and cross-play support across PlayStation, Xbox and PC.',
//     specs: [
//       { label: 'Format', value: 'Blu-ray disc' },
//       { label: 'Platform', value: 'PS4 / PS5 / Xbox' },
//     ],
//     stock: 65,
//   },
// ];
export const consoleProducts = [
  {
    id: 'c-ps5-console',
    name: 'PlayStation 5 Console',
    category: 'consoles',
    platform: 'PlayStation 5',
    brand: 'Sony',
    price: 449.0,
    compareAt: 499.0,
    rating: 4.9,
    reviews: 2210,
    tag: 'Deal',
    colors: ['#FDFCFA'],
    images: [img('ps5-1'), img('ps5-2')],
    img: '/img/ps5.png',
    short: 'Next-generation PlayStation console with fast loading and 4K gaming.',
    description:
      'The PlayStation 5 delivers fast loading, immersive gameplay and stunning graphics for the latest games.',
    specs: [
      { label: 'Storage', value: '825GB SSD' },
      { label: 'Output', value: 'Up to 4K' },
      { label: 'Controller', value: 'DualSense included' },
    ],
    stock: 14,
  },

  {
    id: 'c-ps4-console',
    name: 'PlayStation 4 Console',
    category: 'consoles',
    platform: 'PlayStation 4',
    brand: 'Sony',
    price: 249.0,
    compareAt: 299.0,
    rating: 4.6,
    reviews: 4110,
    tag: 'Deal',
    colors: ['#171512'],
    images: [img('ps4-1'), img('ps4-2')],
    img: '/img/ps4.png',
    short: 'Classic PlayStation console with a huge game library.',
    description:
      'The PlayStation 4 offers a large collection of games, entertainment and reliable everyday gaming performance.',
    specs: [
      { label: 'Storage', value: '500GB HDD' },
      { label: 'Output', value: '1080p HDR' },
      { label: 'Brand', value: 'Sony' },
    ],
    stock: 20,
  },

  {
    id: 'c-ps4-pro',
    name: 'PlayStation 4 Pro',
    category: 'consoles',
    platform: 'PlayStation 4',
    brand: 'Sony',
    price: 299.0,
    compareAt: 349.0,
    rating: 4.7,
    reviews: 1860,
    tag: 'Deal',
    colors: ['#171512'],
    images: [img('ps4pro-1'), img('ps4pro-2')],
    img: '/img/ps4pro.png',
    short: 'Enhanced PS4 console with improved graphics and performance.',
    description:
      'The PS4 Pro provides enhanced graphics and smoother performance for compatible PlayStation games.',
    specs: [
      { label: 'Storage', value: '1TB HDD' },
      { label: 'Output', value: 'Up to 4K' },
      { label: 'HDR', value: 'Supported' },
    ],
    stock: 9,
  },

  {
    id: 'c-ps4-slim',
    name: 'PlayStation 4 Slim',
    category: 'consoles',
    platform: 'PlayStation 4',
    brand: 'Sony',
    price: 229.0,
    compareAt: 279.0,
    rating: 4.6,
    reviews: 1640,
    tag: null,
    colors: ['#171512'],
    images: [img('ps4slim-1'), img('ps4slim-2')],
    img: '/img/ps4slim.png',
    short: 'Compact PS4 console with a slim and quiet design.',
    description:
      'A smaller PS4 design that delivers the familiar PlayStation experience while taking up less space.',
    specs: [
      { label: 'Storage', value: '500GB HDD' },
      { label: 'Output', value: '1080p HDR' },
      { label: 'Design', value: 'Slim' },
    ],
    stock: 14,
  },

  {
    id: 'c-xbox-console',
    name: 'Xbox Console',
    category: 'consoles',
    platform: 'Xbox',
    brand: 'Microsoft',
    price: 399.0,
    compareAt: 449.0,
    rating: 4.7,
    reviews: 1876,
    tag: 'Deal',
    colors: ['#171512'],
    images: [img('xbox-1'), img('xbox-2')],
    img: '/img/xbox.png',
    short: 'Powerful Xbox console built for smooth modern gaming.',
    description:
      'Enjoy fast loading, high-resolution gaming and access to a large library of Xbox titles.',
    specs: [
      { label: 'Storage', value: '1TB SSD' },
      { label: 'Output', value: 'Up to 4K' },
      { label: 'Brand', value: 'Microsoft' },
    ],
    stock: 16,
  },

  {
    id: 'c-ps5-controller',
    name: 'PS5 Wireless Controller',
    category: 'consoles',
    platform: 'PlayStation 5',
    brand: 'Sony',
    price: 64.99,
    compareAt: 74.99,
    rating: 4.7,
    reviews: 980,
    tag: null,
    colors: ['#FDFCFA', '#171512'],
    images: [img('ps5controller-1'), img('ps5controller-2')],
    img: '/img/controller3.png',
    short: 'DualSense wireless controller with haptic feedback.',
    description:
      'A comfortable PS5 controller with responsive controls, haptic feedback and adaptive triggers.',
    specs: [
      { label: 'Connectivity', value: 'Bluetooth / USB-C' },
      { label: 'Compatibility', value: 'PS5' },
      { label: 'Features', value: 'Haptic feedback' },
    ],
    stock: 55,
  },

  {
    id: 'c-ps4-controller',
    name: 'PS4 Wireless Controller',
    category: 'consoles',
    platform: 'PlayStation 4',
    brand: 'Sony',
    price: 49.99,
    compareAt: 59.99,
    rating: 4.6,
    reviews: 760,
    tag: null,
    colors: ['#171512'],
    images: [img('ps4controller-1'), img('ps4controller-2')],
    img: '/img/controller.png',
    short: 'Wireless controller designed for PlayStation 4.',
    description:
      'A comfortable wireless controller with responsive buttons and precise controls for PS4 gaming.',
    specs: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Compatibility', value: 'PS4' },
      { label: 'Charging', value: 'USB' },
    ],
    stock: 35,
  },

  {
    id: 'c-game-witcher',
    name: 'The Witcher 3',
    category: 'consoles',
    platform: 'Games & CDs',
    brand: 'CD Projekt',
    price: 29.99,
    compareAt: 39.99,
    rating: 4.9,
    reviews: 2540,
    tag: 'Deal',
    colors: ['#171512'],
    images: [img('game1'), img('game2')],
    img: '/img/game1.jpg',
    short: 'Open-world RPG set in a massive fantasy world.',
    description:
      'Explore a detailed fantasy world, complete quests and battle monsters in this story-driven action RPG.',
    specs: [
      { label: 'Format', value: 'Game disc' },
      { label: 'Genre', value: 'Action RPG' },
      { label: 'Mode', value: 'Single-player' },
    ],
    stock: 42,
  },

  {
    id: 'c-game-spiderman',
    name: 'Spider-Man Remastered',
    category: 'consoles',
    platform: 'Games & CDs',
    brand: 'Marvel',
    price: 39.99,
    compareAt: 49.99,
    rating: 4.8,
    reviews: 1870,
    tag: 'New',
    colors: ['#171512'],
    images: [img('game3'), img('game4')],
    img: '/img/game3.jpg',
    short: 'Action-packed Spider-Man adventure with open-world gameplay.',
    description:
      'Swing through the city, fight villains and experience a cinematic superhero adventure.',
    specs: [
      { label: 'Format', value: 'Game disc' },
      { label: 'Genre', value: 'Action Adventure' },
      { label: 'Mode', value: 'Single-player' },
    ],
    stock: 30,
  },
];
export const getConsoleProductsByPlatform = (platform) =>
  platform === 'All' ? consoleProducts : consoleProducts.filter((p) => p.platform === platform);

// ── Cameras & lenses ─────────────────────────────────────────
export const cameraProducts = [
  {
    id: 'p-ps4',
    name: 'Lumen R100 DSLR Camera with 18-55mm Lens',
    category: 'cameras',
    brand: 'Lumen',
    price: 239.99,
    compareAt: 304.89,
    rating: 4.5,
    reviews: 612,
    tag: 'Pre Owned',
    colors: ['#171512'],
    img: '/img/ps4.png' ,
    images: [img('cam-r100-1'), img('cam-r100-2')],
    short: 'Entry-level DSLR kit, refurbished and inspected.',
    description:
      'A dependable entry point into interchangeable-lens photography. Each unit is inspected and functionally tested before listing, with a warranty included.',
    specs: [
      { label: 'Sensor', value: '24.1MP APS-C' },
      { label: 'Lens included', value: '18-55mm kit lens' },
      { label: 'Condition', value: 'Pre-owned, inspected' },
    ],
    stock: 9,
  },
  {
    id: 'cam-lumen-r200',
    name: 'Lumen R200 Mirrorless Camera Body',
    category: 'cameras',
    brand: 'Lumen',
    price: 649.99,
    compareAt: 2209.95,
    rating: 4.7,
    reviews: 284,
    tag: 'Pre Owned',
    colors: ['#171512'],
    img: '/img/ps5.png' ,
    images: [img('cam-r200-1'), img('cam-r200-2')],
    short: 'Full-frame mirrorless body, ideal for low-light work.',
    description:
      'A full-frame sensor and fast autofocus make this a capable body for events and portraits, sold body-only and fully tested.',
    specs: [
      { label: 'Sensor', value: '30.4MP full-frame' },
      { label: 'Condition', value: 'Pre-owned, inspected' },
    ],
    stock: 5,
  },
  {
    id: 'cam-lumen-zoom',
    name: 'Lumen Zoom 70-300mm f/4-5.6 Lens',
    category: 'lenses',
    brand: 'Lumen',
    price: 189.99,
    compareAt: 469.9,
    rating: 4.4,
    reviews: 176,
    tag: 'Pre Owned',
    colors: ['#171512'],
    img: '/img/ps5.png' ,
    images: [img('lens-zoom-1'), img('lens-zoom-2')],
    short: 'Telephoto zoom for wildlife, sport and portraits.',
    description:
      'Reach further without swapping bodies — this telephoto zoom covers portraits through distant wildlife with steady, sharp results.',
    specs: [
      { label: 'Focal length', value: '70-300mm' },
      { label: 'Aperture', value: 'f/4-5.6' },
    ],
    stock: 12,
  },
  {
    id: 'cam-lumen-prime',
    name: 'Lumen Prime 50mm f/1.8 Lens',
    category: 'lenses',
    brand: 'Lumen',
    price: 99.99,
    compareAt: null,
    rating: 4.8,
    reviews: 890,
    tag: null,
    colors: ['#171512'],
    img: '/img/ps5.png' ,
    images: [img('lens-prime-1'), img('lens-prime-2')],
    short: 'The classic first prime — sharp, fast, and compact.',
    description:
      'A wide f/1.8 aperture and compact body make this the lens most photographers reach for first, ideal for portraits and low light.',
    specs: [
      { label: 'Focal length', value: '50mm' },
      { label: 'Aperture', value: 'f/1.8' },
    ],
    stock: 30,
  },
];

export const newArrivalIds = [
  'c-ps5-console',
  'p-ps4',
  'p-ps4-pro',
  'p-ps4-slim',
  'p-spiderman',
  'p-witcher-3',
  'p-headphone',
  'p-xbox-controller'
];

// ── Homepage "for you" rail (curated subset) ────────────────
export const recentlyViewedIds = ['p-sneaker-black', 'p-sneaker-air', 'p-sneaker-adidas', 'p-sneaker-cloud'];
export const topSellerIds = ['p-cable-lightning', 'p-monitor-24', 'p-cooker-instant', 'p-hairdryer-philips', 'p-pan-greenpan'];
export const pickedForYouIds = ['p-mouse-xiaomi', 'p-watch-instant', 'p-headphone-razer', 'p-earbuds-sennheiser', 'p-earbuds-xiaomi'];

export const lifestyleBanners = [
  {
    id: 'her',
    title: 'Comfort, considered',
    copy: 'Everyday pieces in soft fabrics, styled for how you actually move through your day.',
    cta: 'Shop the edit',
    image: img('lifestyle-woman', 700, 800),
    img: '/img/ps5.png' ,
  },
  {
    id: 'him',
    title: 'Built for the weekday',
    copy: 'Layers, watches and bags that carry over from desk to dinner without a second thought.',
    cta: 'Shop the edit',
    image: img('lifestyle-man', 700, 800),
    img: '/img/ps5.png' ,
  },

];

export const utilityCategories = [
  { name: 'Siderman Remasterd', img: '/img/game3.jpg' , image: img('util-vacuum', 200, 200) },
  { name: 'Ps4 Controller', img: '/img/controller.png' , image: img('util-console', 200, 200) },
  { name: 'Elden ring',img: '/img/game1.jpg' , image: img('util-speaker', 200, 200) },
  { name: 'headphone', img: '/img/headphone.png' , image: img('util-projector', 200, 200) },
];

export const footerColumns = [
  {
    title: 'Get to know us',
    links: ['Careers', 'Our blog', 'About Verve', 'Investor relations', 'Verve devices', 'Verve tours'],
  },
  {
    title: 'Make money with us',
    links: ['Sell on Verve', 'Sell your apps', 'Become an affiliate', 'Advertise your products', 'Self-publish with us'],
  },
  {
    title: 'Let us help you',
    links: ['Your account', 'Your orders', 'Shipping rates & policies', 'Returns & replacements', 'Help center'],
  },
];

export const currency = '$';

export const allProducts = [...products, ...consoleProducts, ...cameraProducts];

export const getProductById = (id) => allProducts.find((p) => p.id === id);
export const getProductsByIds = (ids) => ids.map(getProductById).filter(Boolean);
